plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.startweld.sncheck'
    compileSdk 34

    defaultConfig {
        applicationId 'ru.startweld.sncheck'
        minSdk 16
        targetSdk 28
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
